Add read by name workaround
pestanko/3scale-api-python pull request #82
Opened 2021-02-11 11:23 UTC by JaurbanRH

Some entities doesn't have properly set entity_e hencenam read_by_name doesn't work on all entites.
@jsmadis @mganisin  please review

2021-02-11 11:27 UTC, mganisin commented
@JaurbanRH would you mind contribute also some test(s). Even trivial would be nice

2021-02-11 15:58 UTC, mkudlej commented
@jaurbanRH would you mind to provide some examples of objects without names?

2021-02-11 17:27 UTC, mkudlej requested changes

2021-02-11 17:27 UTC, mkudlej commented on tests/integration/conftest.py
> +def account_plan(account_plans_params, api):
I think in this case is better to fix account plan
`class AccountPlan(DefaultResource):
    def __init__(self, entity_name='name', **kwargs):  <--- system_name to name
        super().__init__(entity_name=entity_name, **kwargs)`

2021-02-11 17:27 UTC, mkudlej commented on threescale_api/defaults.py
> +            if item.get("name") == name:
I know in description of function is that it searches in system_name, name and org_name, but I don't recommend to change this and I prefer to fix account plan definition.

2021-02-15 09:15 UTC, mkudlej commented on tests/integration/conftest.py
> +def account_plan(account_plans_params, api):
@jsmadis @mganisin What do you think about my proposal?

2021-02-16 09:35 UTC, mkudlej approved these changes
LGTM

2021-02-16 10:12 UTC, jsmadis approved these changes

2021-02-16 10:13 UTC, merged